security:
    encoders:
        AppBundle\Entity\User: plaintext
#            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        chain_provider:
                chain:
                    providers: [in_memory, database_provider]
        in_memory:
            memory:
              users:
                test:
                    password: test
                    roles: 'ROLE_ADMIN'
                test2:
                    password: test2
                    roles: 'ROLE_ADMIN'
        database_provider:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            logout: true
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /user/home/index
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /login
    access_control:
#        - { path: ^/login/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/*, roles: ROLE_USER }